htaccess.settings:
  type: mapping
  label: Settings
  mapping:
    htaccess_settings_url_prefix_redirection:
      type: string
    htaccess_settings_symlinks:
      type: string
    htaccess_settings_ssl:
      type: string
    htaccess_settings_custom_settings:
      type: string
    htaccess_settings_boost_module_rules:
      type: string
    htaccess_altered:
      type: boolean
